import {test,expect} from '@playwright/test';
test('register, search, update, link and delete a physical record',async({page})=>{
  await page.goto('/');
  await page.getByRole('button',{name:'登记文件',exact:true}).click();
  await page.locator('[name="title"]').fill('自动化收文登记测试');
  await page.locator('[name="sender"]').fill('综合测试部');
  await page.locator('[name="location"]').fill('C柜第3层');
  await page.locator('#tag-input').fill('测试');
  await page.locator('#tag-input').press('Enter');
  await page.locator('#tag-input').fill('合同');
  await page.locator('#tag-input').press('Enter');
  await page.getByRole('checkbox',{name:'第三季度重点工作任务分解表 收文'}).check();
  await page.getByRole('button',{name:'保存记录',exact:true}).click();
  await expect(page.locator('.detail-body h2')).toHaveText('自动化收文登记测试');
  await expect(page.locator('.detail-body')).toContainText('C柜第3层');
  await expect(page.locator('.detail-body .relation-item')).toContainText('第三季度重点工作任务分解表');
  await page.getByRole('textbox',{name:'搜索文件'}).fill('自动化收文');
  await expect(page.locator('tbody tr')).toHaveCount(1);
  await page.getByRole('button',{name:'编辑记录',exact:true}).click();
  await page.locator('[name="title"]').fill('自动化收文已修改');
  await page.locator('[name="status"]').selectOption('archived');
  await page.getByRole('button',{name:'保存记录',exact:true}).click();
  await expect(page.locator('.detail-body h2')).toHaveText('自动化收文已修改');
  await page.getByRole('button',{name:'删除记录',exact:true}).click();
  await page.locator('#confirm-delete').click();
  await expect(page.getByRole('heading',{name:'没有找到匹配的文件'})).toBeVisible();
});
test('outgoing fields, tag navigation, reverse relations and safe rendering',async({page})=>{
  await page.goto('/');
  await page.locator('.nav-item[data-nav="outgoing"]').click();
  await page.getByRole('button',{name:'登记文件',exact:true}).click();
  await expect(page.locator('[name="sentAt"]')).toBeVisible();
  await expect(page.locator('[name="receivedAt"]')).toBeHidden();
  await page.locator('[name="title"]').fill('<img src=x onerror=alert(1)>');
  await page.getByRole('button',{name:'保存记录',exact:true}).click();
  await expect(page.locator('.detail-body h2')).toHaveText('<img src=x onerror=alert(1)>');
  await expect(page.locator('.detail-body h2 img')).toHaveCount(0);
  await page.locator('.nav-item[data-nav="links"]').click();
  await expect(page.locator('.relationship-card').filter({has:page.locator('h3',{hasText:'第三季度重点工作任务分解表'})})).toContainText('关于开展第三季度工作总结的通知');
  await page.locator('.nav-item[data-nav="tags"]').click();
  await page.locator('.tag-card').filter({hasText:'安全管理'}).click();
  await expect(page.locator('tbody tr')).toHaveCount(2);
});
test('security and backup pages and session locking',async({page})=>{
  await page.goto('/');
  await page.locator('.nav-item[data-nav="settings"]').click();
  await page.getByRole('button',{name:/同步与备份/}).click();
  await expect(page.getByRole('heading',{name:'本地备份',exact:true})).toBeVisible();
  await expect(page.getByRole('button',{name:'立即备份',exact:true})).toBeDisabled();
  await page.locator('.nav-item[data-nav="settings"]').click();
  await expect(page.getByRole('heading',{name:/设置/})).toBeVisible();
  await expect(page.getByRole('heading',{name:'TOTP 二次验证',exact:true})).toHaveCount(0);
  await page.getByRole('button',{name:/安全与隐私/}).click();
  await expect(page.getByRole('heading',{name:'TOTP 二次验证',exact:true})).toBeVisible();
  await expect(page.locator('[name="autoLockMinutes"] option')).toHaveCount(7);
  await page.locator('[name="autoLockMinutes"]').selectOption('480');
  await page.getByRole('button',{name:'保存安全设置',exact:true}).click();
  await expect(page.locator('[name="autoLockMinutes"]')).toHaveValue('480');
  await page.getByRole('button',{name:'锁定归档库',exact:true}).click();
  await expect(page.getByRole('heading',{name:'欢迎回来'})).toBeVisible();
  await expect(page.locator('tbody')).toHaveCount(0);
});
test('overview visual baseline and no horizontal overflow',async({page})=>{
  await page.goto('/');
  await expect(page.locator('.stat-card')).toHaveCount(4);
  await expect(page.locator('tbody tr')).toHaveCount(0);
  await expect(page.getByRole('heading',{name:'当前待办',exact:true})).toBeVisible();
  expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBeTruthy();
  await page.screenshot({path:'test-results/overview.png',fullPage:true});
});

test('request and other document types use signed date only and three status values',async({page})=>{
  await page.goto('/');
  await page.getByRole('button',{name:'登记文件',exact:true}).click();
  await page.locator('input[value="request"]').check();
  await expect(page.locator('label.field').filter({hasText:'拟稿部门'})).toBeVisible();
  await expect(page.locator('label.field').filter({hasText:'主送领导'})).toBeVisible();
  await page.locator('[name="sender"]').fill('综合管理部');
  await page.locator('[name="recipient"]').fill('分管领导');
  await page.locator('[name="handler"]').fill('张三');
  await expect(page.locator('[name="signedAt"]')).toBeVisible();
  await expect(page.locator('[name="receivedAt"]')).toBeHidden();
  await expect(page.locator('[name="sentAt"]')).toBeHidden();
  await expect(page.locator('[name="status"] option')).toHaveCount(3);
  await page.locator('[name="title"]').fill('只显示已填写字段的请示');
  await page.locator('[name="status"]').selectOption('processing');
  await page.getByRole('button',{name:'保存记录',exact:true}).click();
  await expect(page.locator('tr[data-select]').filter({hasText:'只显示已填写字段的请示'}).locator('.type-badge.request')).toContainText('请示');
  await expect(page.locator('.detail-body')).toContainText('办件中');
  await expect(page.locator('.detail-body')).toContainText('拟稿部门');
  await expect(page.locator('.detail-body')).toContainText('主送领导');
  await expect(page.locator('.detail-body')).toContainText('经办人');
  await expect(page.locator('.detail-body')).not.toContainText('发件人 / 部门');
  await expect(page.locator('.detail-body')).not.toContainText('实体文件存放位置');
  await expect(page.locator('.detail-body')).not.toContainText('备注');
});

test('tag suggestions, location catalog and appearance settings are editable',async({page})=>{
  await page.goto('/');
  await page.getByRole('button',{name:'登记文件',exact:true}).click();
  await page.locator('#tag-input').fill('工作');
  await expect(page.locator('[data-suggest-tag="工作通知"]')).toBeVisible();
  await page.locator('#tag-input').press('ArrowDown');
  await page.locator('#tag-input').press('Enter');
  await expect(page.locator('#tag-chips .tag-chip')).toContainText('工作计划');
  await page.locator('[data-remove-tag="工作计划"]').click();
  await expect(page.locator('#tag-chips .tag-chip')).toHaveCount(0);
  await page.getByRole('button',{name:'取消',exact:true}).click();
  await page.locator('.nav-item[data-nav="settings"]').click();
  await page.getByRole('button',{name:/档案资料/}).click();
  await page.getByRole('button',{name:/物理位置/}).click();
  await page.locator('#location-form input[name="location"]').fill('新建档案柜');
  await page.getByRole('button',{name:'新增位置',exact:true}).click();
  await expect(page.locator('.managed-location').filter({hasText:'新建档案柜'})).toHaveCount(1);
  await page.locator('.managed-location').filter({hasText:'新建档案柜'}).locator('[data-edit-location]').click();
  await page.locator('#edit-location-form input[name="location"]').fill('新建档案柜-已改');
  await page.getByRole('button',{name:'保存位置',exact:true}).click();
  await expect(page.locator('.managed-location').filter({hasText:'新建档案柜-已改'})).toHaveCount(1);
  await page.locator('.nav-item[data-nav="settings"]').click();
  await page.getByRole('button',{name:/外观与字体/}).click();
  await page.locator('[name="theme"]').selectOption('dim');
  await page.locator('[name="fontZh"]').selectOption('SimSun');
  await page.getByRole('button',{name:'保存外观',exact:true}).click();
  await expect(page.locator('html[data-theme="dim"]')).toHaveCount(1);
  await page.locator('.nav-item[data-nav="all"]').click();
  await page.getByRole('button',{name:'登记文件',exact:true}).click();
  await page.locator('[name="location"]').fill('新建档案柜');
  await expect(page.getByRole('option',{name:'新建档案柜-已改',exact:true})).toBeVisible();
  await page.getByRole('option',{name:'新建档案柜-已改',exact:true}).click();
  await expect(page.locator('[name="location"]')).toHaveValue('新建档案柜-已改');
});
test('settings are split into focused subpages with bounded appearance controls',async({page})=>{
  await page.goto('/');
  await page.locator('.nav-item[data-nav="settings"]').click();
  await expect(page.getByRole('heading',{name:/设置/})).toBeVisible();
  await expect(page.locator('.sidebar .settings-subnav')).toHaveCount(0);
  await page.getByRole('button',{name:/安全与隐私/}).click();
  await expect(page.getByRole('heading',{name:'本地加密',exact:true})).toBeVisible();
  await expect(page.getByRole('heading',{name:'TOTP 二次验证',exact:true})).toBeVisible();
  await page.locator('.settings-back [data-nav="settings"]').click();
  await page.getByRole('button',{name:/外观与字体/}).click();
  await expect(page.getByRole('heading',{name:'外观与字体',exact:true})).toBeVisible();
  await expect(page.locator('[name="accent"] option')).toHaveCount(4);
  await expect(page.locator('[name="fontScale"]')).toHaveAttribute('min','0.9');
  await expect(page.locator('[name="fontScale"]')).toHaveAttribute('max','1.15');
  await page.locator('.settings-back [data-nav="settings"]').click();
  await page.getByRole('button',{name:/档案资料/}).click();
  await expect(page.getByRole('heading',{name:/档案资料/})).toBeVisible();
  await page.getByRole('button',{name:/文号模板/}).click();
  await expect(page.getByRole('heading',{name:/文号模板/})).toBeVisible();
  await page.locator('#number-template-form input[name="template"]').fill('校〔2026〕');
  await page.getByRole('button',{name:'新增模板',exact:true}).click();
  await expect(page.locator('.managed-record').filter({hasText:'校〔2026〕'})).toHaveCount(1);
  await page.locator('.settings-back [data-nav="settings-archive"]').click();
  await page.locator('.settings-back [data-nav="settings"]').click();
  await page.getByRole('button',{name:/同步与备份/}).click();
  await expect(page.getByRole('heading',{name:'本地备份',exact:true})).toBeVisible();
});
test('department records support hierarchy, optional leaders and request autofill',async({page})=>{
  await page.goto('/');
  await page.locator('.nav-item[data-nav="settings"]').click();
  await page.getByRole('button',{name:/档案资料/}).click();
  await page.getByRole('button',{name:/单位与领导/}).click();
  await page.locator('[name="name"]').fill('测试部门');
  await page.locator('[name="leaders"]').fill('甲领导,乙领导');
  await page.getByRole('button',{name:'保存部门',exact:true}).click();
  await expect(page.locator('.department-record').filter({hasText:'测试部门'})).toContainText('甲领导、乙领导');
  await page.locator('[name="name"]').fill('测试子部门');
  await page.locator('[name="parentId"]').selectOption({label:'测试部门'});
  await page.getByRole('button',{name:'保存部门',exact:true}).click();
  await expect(page.locator('.department-record').filter({hasText:'测试子部门'})).toBeVisible();
  await page.getByRole('button',{name:'清空',exact:true}).click();
  await page.locator('[name="name"]').fill('单领导部门');
  await page.locator('[name="leaders"]').fill('唯一领导');
  await page.getByRole('button',{name:'保存部门',exact:true}).click();
  await page.locator('.nav-item[data-nav="all"]').click();
  await page.getByRole('button',{name:'登记文件',exact:true}).click();
  await page.locator('input[value="request"]').check();
  await page.locator('[name="sender"]').fill('单领导部门');
  await expect(page.locator('[name="recipient"]')).toHaveValue('唯一领导');
  await expect(page.locator('[name="sender"]')).toHaveAttribute('autocomplete','off');
  await expect(page.locator('[name="location"]')).toHaveAttribute('autocomplete','off');
  await expect(page.locator('[name="recipient"]')).toHaveAttribute('role','combobox');
  await page.locator('[name="sender"]').fill('测试部门');
  await page.locator('[name="recipient"]').fill('');
  await expect(page.getByRole('option',{name:'甲领导',exact:true})).toBeVisible();
  await expect(page.getByRole('option',{name:'乙领导',exact:true})).toBeVisible();
  await page.locator('[name="recipient"]').press('ArrowDown');
  await page.locator('[name="recipient"]').press('ArrowDown');
  await page.locator('[name="recipient"]').press('Enter');
  await expect(page.locator('[name="recipient"]')).toHaveValue('乙领导');
});
test('accent theme reaches login and document type switch without login scrolling',async({page})=>{
  await page.goto('/');
  await page.locator('.nav-item[data-nav="settings"]').click();
  await page.getByRole('button',{name:/外观与字体/}).click();
  await page.locator('[name="accent"]').selectOption('#c24168');
  await page.getByRole('button',{name:'保存外观',exact:true}).click();
  await page.locator('.nav-item[data-nav="all"]').click();
  await page.getByRole('button',{name:'登记文件',exact:true}).click();
  await expect(page.locator('html[data-palette="berry"]')).toHaveCount(1);
  await expect(page.locator('.type-switch input:checked + span')).toBeVisible();
  await page.getByRole('button',{name:'取消',exact:true}).click();
  await page.getByRole('button',{name:'锁定归档库',exact:true}).click();
  await expect(page.getByRole('heading',{name:'欢迎回来'})).toBeVisible();
  await expect(page.locator('html[data-palette="berry"]')).toHaveCount(1);
  expect(await page.evaluate(()=>document.documentElement.scrollHeight<=innerHeight)).toBeTruthy();
});
